/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRendimientoRouteImport } from './routes/_authenticated/rendimiento'
import { Route as AuthenticatedRegistroRouteImport } from './routes/_authenticated/registro'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedAnalisisRouteImport } from './routes/_authenticated/analisis'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRendimientoRoute =
  AuthenticatedRendimientoRouteImport.update({
    id: '/rendimiento',
    path: '/rendimiento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegistroRoute = AuthenticatedRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalisisRoute = AuthenticatedAnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/analisis': typeof AuthenticatedAnalisisRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/registro': typeof AuthenticatedRegistroRoute
  '/rendimiento': typeof AuthenticatedRendimientoRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/analisis': typeof AuthenticatedAnalisisRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/registro': typeof AuthenticatedRegistroRoute
  '/rendimiento': typeof AuthenticatedRendimientoRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analisis': typeof AuthenticatedAnalisisRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/registro': typeof AuthenticatedRegistroRoute
  '/_authenticated/rendimiento': typeof AuthenticatedRendimientoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analisis'
    | '/importar'
    | '/registro'
    | '/rendimiento'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/analisis' | '/importar' | '/registro' | '/rendimiento' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analisis'
    | '/_authenticated/importar'
    | '/_authenticated/registro'
    | '/_authenticated/rendimiento'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rendimiento': {
      id: '/_authenticated/rendimiento'
      path: '/rendimiento'
      fullPath: '/rendimiento'
      preLoaderRoute: typeof AuthenticatedRendimientoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registro': {
      id: '/_authenticated/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof AuthenticatedRegistroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analisis': {
      id: '/_authenticated/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AuthenticatedAnalisisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalisisRoute: typeof AuthenticatedAnalisisRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedRegistroRoute: typeof AuthenticatedRegistroRoute
  AuthenticatedRendimientoRoute: typeof AuthenticatedRendimientoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalisisRoute: AuthenticatedAnalisisRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedRegistroRoute: AuthenticatedRegistroRoute,
  AuthenticatedRendimientoRoute: AuthenticatedRendimientoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
