"use client";

import { useState } from "react";
import { CloseMonthModal } from "./CloseMonthModal";
import { OpenPeriodModal } from "./OpenPeriodModal";
import { useActivePeriod } from "@/features/bankroll/hooks/useMonthlyPeriods";
import { fEUR } from "@/shared/lib/formatters";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CalendarDays, CalendarPlus, CheckCircle2, Loader2 } from "lucide-react";

// ── Props ───────────────────────────────────────────────────────────────────

interface ActivePeriodBannerProps {
  /** Current bankroll to pre-fill closing balance (opening + bets profit) */
  currentBankroll: number;
  /** Profit generated by bets within this period */
  periodProfit: number;
}

// ── Helpers ─────────────────────────────────────────────────────────────────

function formatPeriodLabel(periodMonth: string): string {
  const d = new Date(periodMonth + "T12:00:00");
  return d.toLocaleDateString("es-ES", { month: "long", year: "numeric" });
}

function daysSince(periodMonth: string): number {
  const start = new Date(periodMonth + "T00:00:00");
  const now = new Date();
  return Math.floor((now.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
}

// ── Component ────────────────────────────────────────────────────────────────

export function ActivePeriodBanner({ currentBankroll, periodProfit }: ActivePeriodBannerProps) {
  const { data: activePeriod, isLoading } = useActivePeriod();
  const [closeModalOpen, setCloseModalOpen] = useState(false);
  const [openModalOpen, setOpenModalOpen] = useState(false);

  if (isLoading) {
    return (
      <div className="flex items-center gap-2 text-muted-foreground text-sm py-1">
        <Loader2 className="h-4 w-4 animate-spin" />
        Loading period…
      </div>
    );
  }

  // ── No active period → prompt to open one ──────────────────────────────────
  if (!activePeriod) {
    return (
      <>
        <div className="flex items-center justify-between rounded-lg border border-dashed border-muted-foreground/30 px-4 py-3 bg-muted/20">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <CalendarPlus className="h-4 w-4" />
            No active period — open one to start tracking monthly performance.
          </div>
          <Button size="sm" variant="outline" onClick={() => setOpenModalOpen(true)}>
            <CalendarPlus className="h-4 w-4 mr-1.5" />
            Open Period
          </Button>
        </div>

        <OpenPeriodModal
          open={openModalOpen}
          onOpenChange={setOpenModalOpen}
          suggestedOpeningBalance={currentBankroll}
        />
      </>
    );
  }

  // ── Active period banner ────────────────────────────────────────────────────
  const days = daysSince(activePeriod.period_month);

  return (
    <>
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-card px-4 py-3">
        {/* Left: period info */}
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10">
            <CalendarDays className="h-4 w-4 text-primary" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-sm font-semibold capitalize">
                {formatPeriodLabel(activePeriod.period_month)}
              </span>
              <Badge variant="outline" className="text-xs text-green-500 border-green-500/30">
                Active
              </Badge>
            </div>
            <p className="text-xs text-muted-foreground">
              Opening {fEUR(activePeriod.opening_balance)} · Day {days + 1}
              {periodProfit !== 0 && (
                <span
                  className={`ml-2 font-medium ${
                    periodProfit >= 0 ? "text-green-500" : "text-red-500"
                  }`}
                >
                  {periodProfit >= 0 ? "+" : ""}
                  {fEUR(periodProfit)} so far
                </span>
              )}
            </p>
          </div>
        </div>

        {/* Right: actions */}
        <div className="flex items-center gap-2">
          <Button
            size="sm"
            variant="outline"
            className="gap-1.5"
            onClick={() => setCloseModalOpen(true)}
          >
            <CheckCircle2 className="h-4 w-4" />
            Close Month
          </Button>
        </div>
      </div>

      <CloseMonthModal
        open={closeModalOpen}
        onOpenChange={setCloseModalOpen}
        period={activePeriod}
        currentBankroll={currentBankroll}
        periodProfit={periodProfit}
      />
    </>
  );
}
